"""Verification dashboard: a single self-contained HTML page comparing the system
against Richmond et al. (2020), plus the programme theory and evidence provenance.

This is the artifact a professor/reviewer opens to judge, at a glance, whether the
machine reproduced the human review — the "what does the output look like" answer.
No server, no external assets (works by double-clicking the file).
"""

from __future__ import annotations

import html
import json
from pathlib import Path

from res_pipeline.core.db import get_connection

_TEMPLATE = """<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Realist Evidence Synthesis — Verification Dashboard</title>
<style>
:root{{--bg:#f7f8fa;--card:#fff;--ink:#1c2230;--muted:#5b6472;--line:#e3e7ee;
--good:#1a7f4b;--warn:#b8860b;--bad:#b23b3b;--accent:#2f5bd0}}
*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--ink);
font-family:'Segoe UI',system-ui,sans-serif;line-height:1.5}}
header{{background:linear-gradient(135deg,#2f5bd0,#5a3fc0);color:#fff;padding:2rem}}
header h1{{margin:0 0 .3rem}}header p{{margin:0;opacity:.9}}
main{{max-width:1150px;margin:0 auto;padding:1.5rem}}
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:1rem;margin:1rem 0}}
.card{{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:1.1rem;
box-shadow:0 1px 3px rgba(0,0,0,.04)}}
.metric{{font-size:2rem;font-weight:700}}.metric small{{font-size:.9rem;color:var(--muted);font-weight:400}}
.label{{color:var(--muted);font-size:.85rem;text-transform:uppercase;letter-spacing:.03em}}
.good{{color:var(--good)}}.warn{{color:var(--warn)}}.bad{{color:var(--bad)}}
h2{{border-bottom:2px solid var(--line);padding-bottom:.4rem;margin-top:2rem}}
table{{width:100%;border-collapse:collapse;font-size:.92rem}}
th,td{{text-align:left;padding:.5rem .6rem;border-bottom:1px solid var(--line);vertical-align:top}}
th{{color:var(--muted);font-weight:600}}
blockquote{{margin:.4rem 0;padding:.6rem .9rem;background:#f0f3fb;border-left:3px solid var(--accent);
font-style:italic;border-radius:0 6px 6px 0}}
.pill{{display:inline-block;padding:.1rem .5rem;border-radius:999px;font-size:.78rem;font-weight:600}}
.pill.pos{{background:#e4f5ea;color:var(--good)}}.pill.neg{{background:#fbe9e9;color:var(--bad)}}
.pill.mix{{background:#fbf3e0;color:var(--warn)}}
.note{{background:#fffbe9;border:1px solid #f0e2b0;border-radius:8px;padding:.8rem 1rem;
font-size:.9rem;color:#6a5b1f;margin:1rem 0}}
.bar{{height:8px;background:var(--line);border-radius:4px;overflow:hidden;margin-top:.4rem}}
.bar>span{{display:block;height:100%;background:var(--accent)}}
footer{{color:var(--muted);font-size:.82rem;text-align:center;padding:2rem}}
</style></head><body>
<header>
<h1>Realist Evidence Synthesis — Verification Dashboard</h1>
<p>Agentic GraphRAG pipeline vs. Richmond et al. (2020), <i>The student is key</i> — worked example for RRE 2026</p>
</header>
<main>
<div class="note"><b>How to read this.</b> The pipeline reproduces the analytic steps of a
realist review (search → screen → CMOC extraction → synthesis → programme theory) under human
adjudication. The metrics below compare its outputs to the human benchmark. This is a research
prototype: LLM-judged metrics require human ratification before publication, and HITL
checkpoints in this run were exercised under delegated authority (recorded in the audit trail).</div>

<h2>1. Verification scorecard</h2>
<div class="grid">{scorecards}</div>

<h2>2. Programme theory (system-generated, v{theory_version})</h2>
<p class="label">Sign-off: {signoff}</p>
<p>{overview}</p>
{sections}

<h2>3. Demi-regularities (recurring CMOC motifs across studies)</h2>
<table><thead><tr><th>Context family</th><th>Driver</th><th>Outcome</th><th>Polarity</th>
<th>Studies</th></tr></thead><tbody>{motifs}</tbody></table>

<h2>4. Contradictions & interpretive resolutions (HITL-3)</h2>
<table><thead><tr><th>Driver</th><th>+ / − studies</th><th>Resolution</th></tr></thead>
<tbody>{contradictions}</tbody></table>

<h2>5. Corpus & extraction summary</h2>
<div class="grid">{corpus_cards}</div>

<footer>Generated by the res_pipeline verification harness · all figures reproducible via
<code>res verify</code> / <code>res report</code> · provenance in PostgreSQL audit_log</footer>
</main></body></html>"""


def _cls(value: float, good: float, warn: float) -> str:
    return "good" if value >= good else ("warn" if value >= warn else "bad")


def _scorecard(label: str, value_html: str, css: str, bar_pct: float | None = None) -> str:
    bar = f'<div class="bar"><span style="width:{bar_pct:.0f}%"></span></div>' if bar_pct is not None else ""
    return (f'<div class="card"><div class="label">{label}</div>'
            f'<div class="metric {css}">{value_html}</div>{bar}</div>')


def build_dashboard(verification_report: dict, out_path: Path) -> None:
    r = verification_report
    s, e, rel = r["screening"], r["entity_coverage"], r["relation_coverage"]
    ff, tc = r["citation_faithfulness"], r["theory_correspondence"]

    scorecards = "".join([
        _scorecard("Screening sensitivity (final)",
                   f"{s['final_sensitivity_after_hitl']:.0%}", "good",
                   s['final_sensitivity_after_hitl'] * 100),
        _scorecard("Entity coverage E01–E47",
                   f"{e['recall']:.0%} <small>{e['matched']}/47</small>",
                   _cls(e['recall'], .7, .45), e['recall'] * 100),
        _scorecard("Relation pattern R01–R40",
                   f"{rel.get('type_recall', 0):.0%} <small>type-level "
                   f"{rel.get('type_recovered', 0)}/40 · strict {rel['recovered']}/40</small>",
                   _cls(rel.get('type_recall', 0), .5, .25), rel.get('type_recall', 0) * 100),
        _scorecard("Citation faithfulness",
                   f"{ff['faithfulness']:.0%} <small>{ff['quotes_resolved']}/{ff['entities']}</small>",
                   _cls(ff['faithfulness'], .8, .6), ff['faithfulness'] * 100),
        _scorecard("Theory correspondence",
                   f"{tc.get('mean_correspondence', 0):.2f} <small>/1.0</small>",
                   _cls(tc.get('mean_correspondence', 0), .7, .4),
                   tc.get('mean_correspondence', 0) * 100),
    ])

    with get_connection() as conn:
        theory_row = conn.execute(
            "SELECT version, theory_json, signed_off_by FROM programme_theories "
            "ORDER BY version DESC LIMIT 1"
        ).fetchone()
        motif_rows = conn.execute(
            "SELECT context_concept, driver_concept, outcome_concept, polarity, "
            "array_length(study_ids,1) AS n, study_ids FROM demi_regularities "
            "ORDER BY n DESC LIMIT 15"
        ).fetchall()
        conflict_rows = conn.execute(
            "SELECT driver_concept, positive_studies, negative_studies, resolution "
            "FROM contradictions WHERE resolution IS NOT NULL ORDER BY id"
        ).fetchall()
        n_studies = conn.execute("SELECT count(*) AS n FROM studies").fetchone()["n"]
        n_cmocs = conn.execute("SELECT count(*) AS n FROM cmocs").fetchone()["n"]
        n_entities = conn.execute("SELECT count(*) AS n FROM entity_instances").fetchone()["n"]
        n_relations = conn.execute(
            "SELECT count(*) AS n FROM typed_relations WHERE constraint_valid"
        ).fetchone()["n"]

    theory = theory_row["theory_json"]
    if isinstance(theory, str):
        theory = json.loads(theory)

    def _fam(x: str) -> str:
        return html.escape(x.split(":")[-1].replace("-", " "))

    sections_html = ""
    for i, sec in enumerate(theory["sections"], 1):
        sections_html += (
            f'<div class="card"><h3>Context {i}: {html.escape(sec["context_label"])}</h3>'
            f'<blockquote>{html.escape(sec["cmoc_statement"])}</blockquote>'
            f'<p>{html.escape(sec["explanation"])}</p>'
            f'<p class="label">Supporting studies: {", ".join(sec["supporting_study_ids"])}</p>'
            + (f'<p><b>Conflicting evidence:</b> {html.escape(sec["contradiction_note"])}</p>'
               if sec.get("contradiction_note") else "")
            + "</div>"
        )

    motifs_html = "".join(
        f'<tr><td>{_fam(m["context_concept"])}</td><td>{_fam(m["driver_concept"])}</td>'
        f'<td>{_fam(m["outcome_concept"])}</td>'
        f'<td><span class="pill {"pos" if m["polarity"]=="positive" else "neg" if m["polarity"]=="negative" else "mix"}">{m["polarity"]}</span></td>'
        f'<td>{m["n"]}</td></tr>'
        for m in motif_rows
    )
    contradictions_html = "".join(
        f'<tr><td>{_fam(c["driver_concept"])}</td>'
        f'<td>+{len(c["positive_studies"])} / −{len(c["negative_studies"])}</td>'
        f'<td>{html.escape(c["resolution"])}</td></tr>'
        for c in conflict_rows
    )
    corpus_cards = "".join([
        _scorecard("Studies", str(n_studies), "good"),
        _scorecard("CMOCs extracted", str(n_cmocs), "good"),
        _scorecard("Entity instances", str(n_entities), "good"),
        _scorecard("Valid typed relations", str(n_relations), "good"),
    ])

    out_path.write_text(_TEMPLATE.format(
        scorecards=scorecards,
        theory_version=theory_row["version"],
        signoff=html.escape(theory_row["signed_off_by"] or "PENDING (HITL-4)"),
        overview=html.escape(theory["overview"]),
        sections=sections_html,
        motifs=motifs_html,
        contradictions=contradictions_html,
        corpus_cards=corpus_cards,
    ), encoding="utf-8")
