"""Reporting: emit the same artifact genres Richmond et al. (2020) published.

Artifacts per run (ARCHITECTURE §6), all written to ``outputs/runs/<run_id>/``:
  * ``prisma_flow.md``          — screening flow with counts (vs Richmond Fig. 1)
  * ``cmoc_evidence_table.md``  — per-paper typed CMOC table with quotes (vs App. S2)
  * ``programme_theory.md``     — context-indexed theory with CMOC statements (vs Fig. 2/3)
  * ``theory_diagram.html``     — interactive Mermaid rendering of the theory chains
  * ``verification_report.md``  — stage-by-stage system-vs-Richmond metrics
  * ``audit_trail.md``          — every decision + human intervention (RAMESES II)
"""

from __future__ import annotations

import json
from pathlib import Path

from res_pipeline.core.db import get_connection

_MERMAID_PAGE = """<!doctype html><html><head><meta charset="utf-8">
<title>Programme Theory — Realist Evidence Synthesis</title>
<script type="module">
import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
mermaid.initialize({{ startOnLoad: true, theme: 'neutral' }});
</script>
<style>body{{font-family:Segoe UI,system-ui,sans-serif;margin:2rem;max-width:1100px}}
h2{{border-bottom:1px solid #ccc;padding-bottom:.3rem}}</style></head><body>
<h1>Programme Theory (system-generated draft)</h1>
<p>Generated by the Realist Evidence Synthesis pipeline. Every chain is grounded in
extracted, span-verified CMOCs; see cmoc_evidence_table.md for provenance.</p>
{sections}
</body></html>"""


def _fetch_theory() -> dict | None:
    with get_connection() as conn:
        row = conn.execute(
            "SELECT version, theory_json, signed_off_by FROM programme_theories "
            "ORDER BY version DESC LIMIT 1"
        ).fetchone()
    if not row:
        return None
    theory = row["theory_json"]
    if isinstance(theory, str):
        theory = json.loads(theory)
    theory["_version"] = row["version"]
    theory["_signed_off_by"] = row["signed_off_by"]
    return theory


def write_prisma(out: Path) -> None:
    with get_connection() as conn:
        n_records = conn.execute("SELECT count(*) AS n FROM studies").fetchone()["n"]
        combined = conn.execute(
            "SELECT decision, count(*) AS n FROM screening_decisions "
            "WHERE decider LIKE 'combined:%' GROUP BY decision"
        ).fetchall()
        human_inc = conn.execute(
            "SELECT count(*) AS n FROM screening_decisions "
            "WHERE decider LIKE 'human:%' AND decision='include'"
        ).fetchone()["n"]
        extracted = conn.execute(
            "SELECT count(DISTINCT study_id) AS n FROM cmocs"
        ).fetchone()["n"]
    tally = {r["decision"]: r["n"] for r in combined}
    out.write_text(
        "# PRISMA-style Flow (benchmark-corpus run)\n\n"
        "> Note: this run operates on the Richmond benchmark corpus (the 28 included\n"
        "> studies); a distractor-pool precision test is a separate verification step.\n\n"
        f"| Stage | n |\n|---|---|\n"
        f"| Records in registry | {n_records} |\n"
        f"| Auto-included (dual-model union) | {tally.get('include', 0)} |\n"
        f"| Auto-excluded | {tally.get('exclude', 0)} |\n"
        f"| Uncertain → HITL-1 | {tally.get('uncertain', 0)} |\n"
        f"| Human-adjudicated includes | {human_inc} |\n"
        f"| Final included | {tally.get('include', 0) + human_inc} |\n"
        f"| Studies with extracted CMOCs | {extracted} |\n",
        encoding="utf-8",
    )


def write_evidence_table(out: Path) -> None:
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT c.study_id, s.title, s.year, c.cmoc_id, c.polarity,
                   c.narrative_statement, c.verifier_support,
                   e.entity_type, e.label, e.verbatim_quote, e.quote_resolved
            FROM cmocs c
            JOIN studies s USING (study_id)
            JOIN entity_instances e USING (cmoc_id)
            ORDER BY c.study_id, c.cmoc_id,
                     array_position(ARRAY['Context','Intervention','Mechanism_Resource',
                                          'Mechanism_Response','Outcome'], e.entity_type)
            """
        ).fetchall()
    lines = ["# CMOC Evidence Table (typed, span-grounded)", ""]
    current_cmoc = None
    for r in rows:
        if r["cmoc_id"] != current_cmoc:
            current_cmoc = r["cmoc_id"]
            lines += [
                "", "---", "",
                f"## {r['study_id']} ({r['year']}) — {r['title'][:80]}",
                f"**CMOC** `{r['cmoc_id']}` · polarity: **{r['polarity']}** · "
                f"verifier support: {r['verifier_support']:.2f}",
                f"> *{r['narrative_statement']}*", "",
                "| Element | Label | Verbatim quote | Span |", "|---|---|---|---|",
            ]
        quote = (r["verbatim_quote"] or "").replace("|", "\\|")[:160]
        lines.append(
            f"| {r['entity_type']} | {r['label']} | {quote} | "
            f"{'resolved' if r['quote_resolved'] else 'UNRESOLVED'} |"
        )
    out.write_text("\n".join(lines), encoding="utf-8")


def write_theory_markdown(out: Path) -> None:
    theory = _fetch_theory()
    if not theory:
        out.write_text("# Programme Theory\n\n_Not yet drafted._", encoding="utf-8")
        return
    lines = [
        f"# Programme Theory (v{theory['_version']})",
        f"_Sign-off: {theory['_signed_off_by'] or 'PENDING (HITL-4)'}_", "",
        theory["overview"], "",
    ]
    for i, s in enumerate(theory["sections"], 1):
        lines += [
            f"## Context {i}: {s['context_label']}", "",
            f"> *{s['cmoc_statement']}*", "",
            s["explanation"], "",
            f"**Supporting studies:** {', '.join(s['supporting_study_ids'])}",
        ]
        if s.get("contradiction_note"):
            lines += ["", f"**Conflicting evidence:** {s['contradiction_note']}"]
        lines.append("")
    lines += ["## Boundary statement", "", theory["boundary_statement"]]
    out.write_text("\n".join(lines), encoding="utf-8")


def write_theory_diagram(out: Path) -> None:
    theory = _fetch_theory()
    if not theory:
        return
    sections_html = []
    for i, s in enumerate(theory["sections"], 1):
        node_context = s["context_label"].replace('"', "'")
        graph = (
            "graph LR\n"
            f'  C{i}["(C) {node_context}"] --> M{i}["(M) mechanism: see statement"]'
            f' --> O{i}["(O) outcomes"]\n'
        )
        sections_html.append(
            f"<h2>Context {i}: {s['context_label']}</h2>"
            f"<blockquote><i>{s['cmoc_statement']}</i></blockquote>"
            f"<pre class=\"mermaid\">{graph}</pre>"
            f"<p><b>Studies:</b> {', '.join(s['supporting_study_ids'])}</p>"
        )
    out.write_text(_MERMAID_PAGE.format(sections="\n".join(sections_html)),
                   encoding="utf-8")


def write_audit_trail(out: Path) -> None:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT created_at, run_id, actor, action, subject_ref, detail "
            "FROM audit_log ORDER BY id"
        ).fetchall()
    lines = ["# Audit Trail", "",
             "| Time (UTC) | Run | Actor | Action | Subject | Detail |", "|---|---|---|---|---|---|"]
    for r in rows:
        detail = json.dumps(r["detail"], default=str)[:120].replace("|", "\\|")
        lines.append(
            f"| {r['created_at']:%Y-%m-%d %H:%M:%S} | {r['run_id']} | {r['actor']} "
            f"| {r['action']} | {r['subject_ref'] or ''} | {detail} |"
        )
    out.write_text("\n".join(lines), encoding="utf-8")


def write_verification_markdown(report: dict, out: Path) -> None:
    s = report["screening"]
    e = report["entity_coverage"]
    r = report["relation_coverage"]
    f = report["citation_faithfulness"]
    t = report["theory_correspondence"]
    lines = [
        "# Verification Report — System vs Richmond et al. (2020)", "",
        "External benchmark evaluation (separate from the production pipeline).", "",
        "## 1. Screening (title/abstract)",
        f"- Gold includes: {s['n_gold_includes']}",
        f"- Auto-include sensitivity: **{s['auto_sensitivity']:.1%}** "
        f"({s['auto_include']}/{s['n_gold_includes']})",
        f"- False excludes: **{len(s['false_excludes'])}** {s['false_excludes'] or ''}",
        f"- Uncertain → HITL-1: {len(s['uncertain_routed_to_hitl'])} "
        f"{s['uncertain_routed_to_hitl']}",
        f"- Final sensitivity after HITL-1: **{s['final_sensitivity_after_hitl']:.1%}**", "",
        "## 2. Entity coverage (47 gold entities E01–E47)",
        f"- Recall: **{e['recall']:.1%}** ({e['matched']}/{e['gold_entities']}) — "
        "LLM-judged semantic matching (human audit required before publication)", "",
        "## 3. Relation coverage (40 gold relations R01–R40)",
        f"- Strict recall (exact concept match on both endpoints): **{r['recall']:.1%}** "
        f"({r['recovered']}/{r['gold_relations']})",
        f"- Type-level recall (causal pattern recovered — predicate + endpoint types): "
        f"**{r.get('type_recall', 0):.1%}** ({r.get('type_recovered', 0)}/{r['gold_relations']})",
        f"- Missed (strict): {', '.join(r['missed_ids']) if r['missed_ids'] else 'none'}", "",
        "## 4. Citation faithfulness (automated, exact)",
        f"- {f['quotes_resolved']}/{f['entities']} extracted elements have verbatim quotes "
        f"resolved to exact character spans: **{f['faithfulness']:.1%}**", "",
        "## 5. Programme-theory correspondence (5 gold PTS chains)",
        f"- Mean correspondence: **{t.get('mean_correspondence', 0):.2f}** "
        f"({t.get('judge','')})", "",
    ]
    if "per_chain" in t:
        lines += ["| PTS | Score | Rationale |", "|---|---|---|"]
        for pts, info in t["per_chain"].items():
            lines.append(f"| {pts} | {info['correspondence']:.2f} | "
                         f"{info['rationale'][:140].replace('|', ' ')} |")
    out.write_text("\n".join(lines), encoding="utf-8")
